### ISSUE TITLE
可以保存导出标注好的图片么

### ISSUE THREAD

**Issue by fuyi501** [dingyang9642/AILabel#28]
可以保存导出标注好的图片么

**Comment by dingyang9642** [comment]
v5.1.1之版本Map对象提供exportLayersToImage方法，可参考api：http://ailabel.com.cn/public/ailabel/api/index.html#231  或者demo文档：http://ailabel.com.cn/public/ailabel/demo/index.html

**Comment by dingyang9642** [comment]
close this issue
