### ISSUE TITLE
标注后的坐标数据能生成特定格式的标注文件吗？

### ISSUE THREAD

**Issue by chaochaozouzou** [dingyang9642/AILabel#6]
1、标注后的label坐标数据，能生成标注文件导出吗？
2、还想请教下，开发这个annotator的技术壁垒在哪里呀？

**Comment by dingyang9642** [comment]
1、标注文件的导出需要依赖平台应用，暂时不提供标注平台进行文件导出，各自业务可使用ailabel进行平台实现
2、主要是事件、对象管理、一些小算法实现
